/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    SchemaRegistry: {
      address:
        "0x029ea3f8f406a659c903a3e02ed102f0a21048fd40639a96f57637aadc1d6999",
      abi: [
        {
          type: "impl",
          name: "SchemaRegistryImpl",
          interface_name: "contracts::SchemaRegistry::ISchemaRegistry",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::SchemaRegistry::ISchemaRegistry",
          items: [
            {
              type: "function",
              name: "register",
              inputs: [
                {
                  name: "schema",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "revocable",
                  type: "core::bool",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u128",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_schema",
              inputs: [
                {
                  name: "uid",
                  type: "core::integer::u128",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u128, core::bool, core::byte_array::ByteArray)",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SchemaRegistry::SchemaRegistry::Registered",
          kind: "struct",
          members: [
            {
              name: "uid",
              type: "core::integer::u128",
              kind: "key",
            },
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "schema_record",
              type: "core::byte_array::ByteArray",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SchemaRegistry::SchemaRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "Registered",
              type: "contracts::SchemaRegistry::SchemaRegistry::Registered",
              kind: "nested",
            },
          ],
        },
      ],
    },
  },
  sepolia: {
    SchemaRegistry: {
      address:
        "0x0011bc1356dda0d57fe748a2f30f53e65f8cc5a16c46be71b495d71004ac9b08",
      abi: [
        {
          type: "impl",
          name: "SchemaRegistryImpl",
          interface_name: "contracts::SchemaRegistry::ISchemaRegistry",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::SchemaRegistry::ISchemaRegistry",
          items: [
            {
              type: "function",
              name: "register",
              inputs: [
                {
                  name: "schema",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "revocable",
                  type: "core::bool",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u128",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_schema",
              inputs: [
                {
                  name: "uid",
                  type: "core::integer::u128",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u128, core::bool, core::byte_array::ByteArray)",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SchemaRegistry::SchemaRegistry::Registered",
          kind: "struct",
          members: [
            {
              name: "uid",
              type: "core::integer::u128",
              kind: "key",
            },
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "schema_record",
              type: "core::byte_array::ByteArray",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SchemaRegistry::SchemaRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "Registered",
              type: "contracts::SchemaRegistry::SchemaRegistry::Registered",
              kind: "nested",
            },
          ],
        },
      ],
    },
    AttestationRegistry: {
      address:
        "0x0755a87fa1f416ad81a1ae94bc29e17bf4a2fa820c61a35ccdcdc08746cd319c",
      abi: [
        {
          type: "impl",
          name: "AttestationRegistryImpl",
          interface_name:
            "contracts::AttestationRegistry::IAttestationRegistry",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::AttestationRegistry::Attestation",
          members: [
            {
              name: "uid",
              type: "core::integer::u128",
            },
            {
              name: "schema_uid",
              type: "core::integer::u128",
            },
            {
              name: "time",
              type: "core::integer::u64",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "attester",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "data",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "revocable",
              type: "core::bool",
            },
            {
              name: "revocation_time",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::AttestationRegistry::IAttestationRegistry",
          items: [
            {
              type: "function",
              name: "get_attestation",
              inputs: [
                {
                  name: "attestation_uid",
                  type: "core::integer::u128",
                },
              ],
              outputs: [
                {
                  type: "contracts::AttestationRegistry::Attestation",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "attest",
              inputs: [
                {
                  name: "schema_uid",
                  type: "core::integer::u128",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "data",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "revocable",
                  type: "core::bool",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u128",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revoke",
              inputs: [
                {
                  name: "schema_uid",
                  type: "core::integer::u128",
                },
                {
                  name: "attestation_uid",
                  type: "core::integer::u128",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "schema_registry_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::AttestationRegistry::AttestationRegistry::Attested",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "attester",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "uid",
              type: "core::integer::u128",
              kind: "data",
            },
            {
              name: "schema_uid",
              type: "core::integer::u128",
              kind: "key",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::AttestationRegistry::AttestationRegistry::Revoked",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "attester",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "schema_uid",
              type: "core::integer::u128",
              kind: "key",
            },
            {
              name: "attestation_uid",
              type: "core::integer::u128",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::AttestationRegistry::AttestationRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "Attested",
              type: "contracts::AttestationRegistry::AttestationRegistry::Attested",
              kind: "nested",
            },
            {
              name: "Revoked",
              type: "contracts::AttestationRegistry::AttestationRegistry::Revoked",
              kind: "nested",
            },
          ],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
